### ISSUE TITLE
https support?

### ISSUE THREAD

**Issue by Zeitkind** [Ellerhold/fs2es-indexer#10]
The default installation of elacticsearch - at least on my Debian 11 - automatically enables TLS & users/password and therefor you need to connect to port 9200 with https:
root@server34:/etc/fs2es-indexer# fs2es-indexer index
2022-02-19 20:30:53 Reading config file "/etc/fs2es-indexer/config.yml"
Traceback (most recent call last):
  File "/usr/bin/fs2es-indexer", line 4, in <module>
    __import__('pkg_resources').run_script('fs2es-indexer==0.3.1', 'fs2es-indexer')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3/dist-packages/fs2es_indexer-0.3.1-py3.9.egg/EGG-INFO/scripts/fs2es-indexer", line 49, in <module>
  File "/usr/lib/python3/dist-packages/fs2es_indexer-0.3.1-py3.9.egg/fs2es_indexer/Fs2EsIndexer.py", line 109, in prepare_index
  File "/usr/local/lib/python3.9/dist-packages/elasticsearch/_sync/client/utils.py", line 404, in wrapped
    return api(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/elasticsearch/_sync/client/indices.py", line 1058, in exists
    return self.perform_request(  # type: ignore[return-value]
  File "/usr/local/lib/python3.9/dist-packages/elasticsearch/_sync/client/_base.py", line 390, in perform_request
    return self._client.perform_request(
  File "/usr/local/lib/python3.9/dist-packages/elasticsearch/_sync/client/_base.py", line 286, in perform_request
    meta, resp_body = self.transport.perform_request(
  File "/usr/local/lib/python3.9/dist-packages/elastic_transport/_transport.py", line 329, in perform_request
    meta, raw_data = node.perform_request(
  File "/usr/local/lib/python3.9/dist-packages/elastic_transport/_node/_http_urllib3.py", line 177, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: ProtocolError(('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))))

So - either re-enable http (which I was not able to find in the docs..) or connect via https (and also accept the self-signed certificate), but https is not supported. Any ideas?

**Comment by MatthiasKuehneEllerhold** [comment]
You can tweak the URL, port, username and password in the configuration. Have you tried this?

**Comment by Zeitkind** [comment]
I digged around a bit, because I recently installed without any problems. Seems that on the older machine I run Elasticsearch v7, on the newer one v8, and v8 enables security features by default during installation. I could reinstall and use the v7 repository, but on the other hand v8 will be the default version any time soon, so.. hmm..
If you upgrade from v7 to v8, it doesn't seem to initiate security settings either.
The newer machine is atm active and I can't touch it now, but the older machine is a testing VM anyway, so I just purged v7 and reinstalled v8:

elasticsearch (8.0.0) wird eingerichtet ...
--------------------------- Security autoconfiguration information ------------------------------
Authentication and authorization are enabled.
TLS for the transport and HTTP layers is enabled and configured.
[...]

Starting fs2es-indexer with https as URL seems to work, but it fails because of the self-signed certificate:

# fs2es-indexer index
2022-02-21 17:48:41 Reading config file "/etc/fs2es-indexer/config.yml"
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/elasticsearch/connection/http_urllib3.py", line 255, in perform_request
    response = self.pool.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 507, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/fs2es-indexer", line 4, in <module>
    __import__('pkg_resources').run_script('fs2es-indexer==0.3.0', 'fs2es-indexer')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3/dist-packages/fs2es_indexer-0.3.0-py3.9.egg/EGG-INFO/scripts/fs2es-indexer", line 49, in <module>
  File "/usr/lib/python3/dist-packages/fs2es_indexer-0.3.0-py3.9.egg/fs2es_indexer/Fs2EsIndexer.py", line 109, in prepare_index
  File "/usr/local/lib/python3.9/dist-packages/elasticsearch/client/utils.py", line 347, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/elasticsearch/client/indices.py", line 371, in exists
    return self.transport.perform_request(
  File "/usr/local/lib/python3.9/dist-packages/elasticsearch/transport.py", line 417, in perform_request
    self._do_verify_elasticsearch(headers=headers, timeout=timeout)
  File "/usr/local/lib/python3.9/dist-packages/elasticsearch/transport.py", line 606, in _do_verify_elasticsearch
    raise error
  File "/usr/local/lib/python3.9/dist-packages/elasticsearch/transport.py", line 569, in _do_verify_elasticsearch
    _, info_headers, info_response = conn.perform_request(
  File "/usr/local/lib/python3.9/dist-packages/elasticsearch/connection/http_urllib3.py", line 277, in perform_request
    raise SSLError("N/A", str(e), e)
elasticsearch.exceptions.SSLError: ConnectionError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)) caused by: SSLError([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123))

**Comment by MatthiasKuehneEllerhold** [comment]
This leads to another thing: ElasticSearch 8 needs the python-elasticsearch v8 library, which is not (yet) supported by fs2es. See #8

Additionally you'd need to disable the SSL verification if you want to use self-signed certificates.

**Comment by Zeitkind** [comment]
Sounds like a looong rabbit hole, could not even find any link on how to disable https again, did not work by simply removing settings in the yml. Well, so I will purge v8 (remove doesn't work) and reinstall v7. The repository URL is getting harder to find, but replacing 8.x by 7.x in the apt.list works anyway..

Working again, although Spotlight search doesn't work at all. Seems enabled ("Server search enabled."), but doesn't find anything, neither file names nor content. Does the script tells Elasticsearch to index inside the files (via the ingest-attachment plugin/tica)?

"Files & directories indexed: 6988"

Searching the index with

curl -X GET http://localhost:9200/index-test/_search?q=Solaris

does find some filenames of manuals (I put there for testing) but nothing inside any .txt, .pdf or whatever.
Spotlight from a Mac via network just finds nothing at all. Hmmm..

**Comment by MatthiasKuehneEllerhold** [comment]
Ive added some options to 0.3.3-beta1, see the configuration file. Could you please test them? 
Running without ssl still works on my end.

**Comment by Zeitkind** [comment]
Hiho,
took me quite some time. Debian style cookbook:
1. get elasticsearch v7, install normal
2. generate users with "/usr/share/elasticsearch/bin/elasticsearch-setup-passwords auto"
3. check with curl -XGET -u elastic:thepasswordyougot 'http://localhost:9200'
4. stop elasticsearch
5. get yourself an easy way to handle certificates, eg. easy-rsa
6. create local CA, add local CA to system trusted (update-ca-certificates)
7. enable basic security in elasticsearch (edit elasticsearch.yml)
  xpack.security.enabled: true
  discovery.type: single-node
  xpack.security.transport.ssl.enabled: true
  xpack.security.http.ssl.enabled: true
  xpack.security.http.ssl.keystore.path: elastic.p12
8. use "/usr/share/elasticsearch/bin/elasticsearch-certutil http" to generate a csr
  be sure to add localhost as SAN!
9. import as eg. "elastic" and sign request with easy-rsa
10. convert crt to elastic.p12, include key-file (format pkcs12)
11. use "/usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.http.ssl.keystore.secure_password" to pass the key password to elasticsearch
12. copy elastic.p12 to /etc/elasticsearch, check permissions (750)
13. prey and start elasticsearch
14. test with
  curl -XGET -u elastic:thepasswordyougot 'https://localhost:9200'
You should get:
{
  "name" : "myservername",
  "cluster_name" : "elasticsearch",
[...]

15. edit "/etc/fs2es-indexer/config.yml" and replace http with https, set user ("elastic") and password
16. check with "fs2es-indexer index"

Comment: As far as I could find, before v7.something encryption and security was bound to a paid license? But I remember several big security incidents with wide open elasticsearch-servers in the net (i.e. not bound to localhost and no users, no encryption) some time ago, so it seems they now offer what they call "basic" security also for the unpaid license. And starting with v8, at least on my Debian, basic security (with https) is enforced during normal installation.

**Comment by MatthiasKuehneEllerhold** [comment]
So... it works? ^^

**Comment by Zeitkind** [comment]
Yes - and no. Indexing works with "basic security" (aka users & TLS) now. I can also check with curl for results, eg. 
curl -X GET -u elastic:yourpassword https://localhost:9200/index-yourindex/_search?q=Apple
without SSL errors (include localhost as SAN in the certificate).
Problem is Samba & Mac, no luck yet. Samba announces server side spotlight, but I don't get any result. Has nothing to do with fs2es-indexer, need to recheck all the smb and share settings and samba version..

**Comment by lamixer** [comment]
I had some problems with Debian 11 Samba. Not sure if I'm about to send you down the wrong path, but have a look in the mac Finder at the permissions with which the Samba share is mounted. Compare to a real AFP drive if you have one, or a real external disk.

**Comment by Zeitkind** [comment]
Thx, but unlikey. I run Debian 11 with backports repo enabled (Samba version 4.13.13-Debian) and with openmediavault installed over it, so it's quite likely that some things got broken...

**Comment by MatthiasKuehneEllerhold** [comment]
Did you set these in your smb.conf?
```ini
elasticsearch:use tls = yes
elasticsearch:user = XY
elasticsearch:password = XY
```

Mh, I see the support for user - auth is not merged into samba yet! There was a PR somewhere though...

**Comment by MatthiasKuehneEllerhold** [comment]
Here is the PR: https://gitlab.com/samba-team/samba/-/merge_requests/1847 
It is not merged yet, so samba currently cant give basic auth details to ES. I dont have any information when this is going to be rdy. Im guessing it wont make it into 4.16 though

**Comment by MatthiasKuehneEllerhold** [comment]
@Zeitkind So HTTPS support & basic auth of the indexer works correctly, yes? Just samba cant give basic auth details (yet)?
Please close this issue then. Thanks!
