### ISSUE TITLE
Mac mdfind doesn't find anything, nor Mac's Finder

### ISSUE THREAD

**Issue by Jsalas424** [Ellerhold/fs2es-indexer#24]
Hi,

I completed debugging steps 1-4 with no problem:

Step 3: 

```
jon@rstudio:/var/log/samba$ fs2es-indexer search --search-path R/Data --search-term test
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.11) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
2022-08-19 17:10:06 Reading config file "/etc/fs2es-indexer/config.yml"
2022-08-19 17:10:06 Found 158 elasticsearch documents:
2022-08-19 17:10:06 - test.pdf: {"path": {"real": "/home/jon/R/Data/.../test.pdf"}, "file": {"filename": "test.pdf", "filesize": 123148}, "time": 1660942038.2375557}
```

Step 4: 
```
jon@Jonathans-MBP-2 ~ % mdutil -s /Volumes/'R Data'    
/System/Volumes/Data/Volumes/R Data:
	Server search enabled.
```

But nothing is returned on step 5 and nothing in the logs:
```
jon@Jonathans-MBP-2 ~ % mdfind -onlyin /Volumes/'R Data' test
```

Mac logs for the query:
```

default	17:11:56.342456-0400	mdfind	Supported compatibility version = 7
default	17:11:56.343002-0400	mdfind	-[MAXpcManager ensureConnection]: Creating client/daemon connection: A6F9461A-3DA6-4CD9-8A72-F1E5A6985D4D
default	17:11:56.343378-0400	mobileassetd	-[ControlManager handleClientConnection:on:]_block_invoke: assetType: com.apple.MobileAsset.LinguisticData client: mdfind, command: 1 (MA_QUERY_ASSET_TYPE)
default	17:11:56.343425-0400	mobileassetd	-[ControlManager handleClientConnection:on:]_block_invoke: mdfind issued query command for com.apple.MobileAsset.LinguisticData
default	17:11:56.343456-0400	mobileassetd	-[ControlManager handleQueryRequest:clientName:connection:message:]: mdfind queried for: com.apple.MobileAsset.LinguisticData with returnType of: 2 (MAUnionOfCatalogInstalled) - will not block on network by client request
default	17:11:56.343575-0400	mobileassetd	-[ControlManager determineAssets:clientName:connection:downloadingTasks:message:resultTypes:queryArray:isForSpecificAsset:specificAssetId:specificAllowedDifferences:]: mdfind queried for: com.apple.MobileAsset.LinguisticData with returnType of: 2 with Purpose: (null)
default	17:11:56.413635-0400	mobileassetd	-[ControlManager determineAssets:clientName:connection:downloadingTasks:message:resultTypes:queryArray:isForSpecificAsset:specificAssetId:specificAllowedDifferences:]: mdfind queried for: com.apple.MobileAsset.LinguisticData with returnTypes 2 (MAUnionOfCatalogInstalled) and found 0 assets with result 0 (MAQuerySuccessful) --> From 745 listed in the catalog and 11 local (11/11 downloaded, 0 preinstalled)--> Catalog info ({     isLiveServer = 0; }) --> Filtered for MAUnionOfCatalogInstalled to 0 in catalog (0 installed, 0 server-only, 0 preinstalled), 0 installedNotInCatalog, 0 installedWithOS, 0 requiredByOS; the query params are: [ AssetLocale:'en' and AssetType:'Delta' and _CompatibilityVersion:'7'] --> Merged to 0 assets
default	17:11:56.413822-0400	mdfind	-[MAAssetQuery getResultsFromMessage:]: Got the query meta data reply for: com.apple.MobileAsset.LinguisticData, response: 0
default	17:11:56.414333-0400	mdfind	assetsForQuery: <query: com.apple.MobileAsset.LinguisticData, locO: 1, iO: 1, latO: 1, <filter: {
    AssetLocale = "{(\n    en\n)}";
    AssetType = "{(\n    Delta\n)}";
}>> final result: (
) was cached: 0, cachedOnly: 0
default	17:11:56.414935-0400	mobileassetd	-[ControlManager handleClientConnection:on:]_block_invoke: assetType: com.apple.MobileAsset.LinguisticData client: mdfind, command: 1 (MA_QUERY_ASSET_TYPE)
default	17:11:56.415004-0400	mobileassetd	-[ControlManager handleClientConnection:on:]_block_invoke: mdfind issued query command for com.apple.MobileAsset.LinguisticData
default	17:11:56.415025-0400	mobileassetd	-[ControlManager handleQueryRequest:clientName:connection:message:]: mdfind queried for: com.apple.MobileAsset.LinguisticData with returnType of: 2 (MAUnionOfCatalogInstalled) - will not block on network by client request
default	17:11:56.417746-0400	mobileassetd	-[ControlManager determineAssets:clientName:connection:downloadingTasks:message:resultTypes:queryArray:isForSpecificAsset:specificAssetId:specificAllowedDifferences:]: mdfind queried for: com.apple.MobileAsset.LinguisticData with returnType of: 2 with Purpose: (null)
default	17:11:56.480716-0400	mobileassetd	-[ControlManager determineAssets:clientName:connection:downloadingTasks:message:resultTypes:queryArray:isForSpecificAsset:specificAssetId:specificAllowedDifferences:]: mdfind queried for: com.apple.MobileAsset.LinguisticData with returnTypes 2 (MAUnionOfCatalogInstalled) and found 1 assets with result 0 (MAQuerySuccessful) --> From 745 listed in the catalog and 11 local (11/11 downloaded, 0 preinstalled)--> Catalog info ({     isLiveServer = 0; }) --> Filtered for MAUnionOfCatalogInstalled to 1 in catalog (1 installed, 0 server-only, 0 preinstalled), 0 installedNotInCatalog, 0 installedWithOS, 0 requiredByOS; the query params are: [ AssetLocale:'en' and AssetType:'Optional' and _CompatibilityVersion:'7'] --> Merged to 1 assets
default	17:11:56.481326-0400	mdfind	-[MAAssetQuery getResultsFromMessage:]: Got the query meta data reply for: com.apple.MobileAsset.LinguisticData, response: 0
default	17:11:56.482008-0400	mobileassetd	-[ControlManager handleClientConnection:on:]_block_invoke: assetType: com.apple.MobileAsset.LinguisticData client: mdfind, command: 7 (MA_GET_SANDBOX_EXTENSION)
default	17:11:56.482372-0400	mdfind	_MAensureExtension: Consumed extension
default	17:11:56.482533-0400	mobileassetd	-[ControlManager handleClientConnection:on:]_block_invoke: assetType: com.apple.MobileAsset.LinguisticData client: mdfind, command: 21 (MA_UPDATE_CLIENT_USAGE)
default	17:11:56.485073-0400	mobileassetd	-[ControlManager handleUpdateClientUsage:using:and:clientName:]_block_invoke: mdfind asset com.apple.MobileAsset.LinguisticData dc4c467a0fffeac78ab819a94e98576bac0c3539 has been used in past 24 hours '/System/Library/AssetsV2/com_apple_MobileAsset_LinguisticData/dc4c467a0fffeac78ab819a94e98576bac0c3539.asset': 16438.897247
default	17:11:56.485179-0400	mobileassetd	-[ControlManager handleUpdateClientUsage:using:and:clientName:]_block_invoke: mdfind client Usage type: com.apple.MobileAsset.LinguisticData id:dc4c467a0fffeac78ab819a94e98576bac0c3539, parent path: '/System/Library/AssetsV2/com_apple_MobileAsset_LinguisticData/dc4c467a0fffeac78ab819a94e98576bac0c3539.asset' AssetData exists
default	17:11:56.485299-0400	mdfind	_MAsendUpdateClientAccessGetPathWithPurposeSync: getLocalPath asset com.apple.MobileAsset.LinguisticData dc4c467a0fffeac78ab819a94e98576bac0c3539 local path is '/System/Library/AssetsV2/com_apple_MobileAsset_LinguisticData/dc4c467a0fffeac78ab819a94e98576bac0c3539.asset/AssetData', exists: YES
default	17:11:56.485500-0400	mdfind	assetsForQuery: <query: com.apple.MobileAsset.LinguisticData, locO: 1, iO: 1, latO: 1, <filter: {
    AssetLocale = "{(\n    en\n)}";
    AssetType = "{(\n    Optional\n)}";
}>> final result: (
    "en-Optional::dc4c467a0fffeac78ab819a94e98576bac0c3539.asset"
) was cached: 0, cachedOnly: 0
default	17:11:56.487361-0400	mdfind	assetsForQuery: <query: com.apple.MobileAsset.LinguisticData, locO: 1, iO: 1, latO: 1, <filter: {
    AssetLocale = "{(\n    en\n)}";
    AssetType = "{(\n    Delta\n)}";
}>> final result: (
) was cached: 1, cachedOnly: 0
default	17:11:56.487533-0400	mdfind	assetsForQuery: <query: com.apple.MobileAsset.LinguisticData, locO: 1, iO: 1, latO: 1, <filter: {
    AssetLocale = "{(\n    en\n)}";
    AssetType = "{(\n    Optional\n)}";
}>> final result: (
    "en-Optional::dc4c467a0fffeac78ab819a94e98576bac0c3539.asset"
) was cached: 1, cachedOnly: 0
default	17:11:56.487992-0400	mdfind	assetsForQuery: <query: com.apple.MobileAsset.LinguisticData, locO: 1, iO: 1, latO: 1, <filter: {
    AssetLocale = "{(\n    en\n)}";
    AssetType = "{(\n    Delta\n)}";
}>> final result: (
) was cached: 1, cachedOnly: 0
default	17:11:56.488131-0400	mdfind	assetsForQuery: <query: com.apple.MobileAsset.LinguisticData, locO: 1, iO: 1, latO: 1, <filter: {
    AssetLocale = "{(\n    en\n)}";
    AssetType = "{(\n    Optional\n)}";
}>> final result: (
    "en-Optional::dc4c467a0fffeac78ab819a94e98576bac0c3539.asset"
) was cached: 1, cachedOnly: 0
default	17:11:56.515276-0400	mdfind	Starting query at qos 0x21
default	17:11:56.517637-0400	tccd	AUTHREQ_ATTRIBUTION: msgID=96.109, attribution={responsible={identifier=com.apple.Terminal, pid=668, auid=501, euid=501, responsible_path=/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal, binary_path=/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal}, accessing={identifier=com.apple.mdfind, pid=1060, auid=501, euid=501, binary_path=/usr/bin/mdfind}, requesting={identifier=com.apple.mds, pid=96, auid=0, euid=0, binary_path=/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Support/mds}, },
default	17:11:56.535495-0400	tccd	AUTHREQ_ATTRIBUTION: msgID=96.110, attribution={responsible={identifier=com.apple.Terminal, pid=668, auid=501, euid=501, responsible_path=/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal, binary_path=/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal}, accessing={identifier=com.apple.mdfind, pid=1060, auid=501, euid=501, binary_path=/usr/bin/mdfind}, requesting={identifier=com.apple.mds, pid=96, auid=0, euid=0, binary_path=/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Support/mds}, },
default	17:11:56.548593-0400	tccd	AUTHREQ_ATTRIBUTION: msgID=96.111, attribution={responsible={identifier=com.apple.Terminal, pid=668, auid=501, euid=501, responsible_path=/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal, binary_path=/System/Applications/Utilities/Terminal.app/Contents/MacOS/Terminal}, accessing={identifier=com.apple.mdfind, pid=1060, auid=501, euid=501, binary_path=/usr/bin/mdfind}, requesting={identifier=com.apple.mds, pid=96, auid=0, euid=0, binary_path=/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Support/mds}, },
default	17:11:56.566934-0400	mdfind	Starting query at qos 0x21
default	17:11:56.570492-0400	mdfind	Starting query at qos 0x21

```

Nothing in the server side logs. 

Elasticsearch v8 with SSL Security features disabled, otherwise vanilla install. 

Thanks in advance!

**Comment by Jsalas424** [comment]
Elasticsearch logs showing everything happy and running:

```
jon@rstudio:/var/log/samba$ sudo tail -f /var/log/elasticsearch/elasticsearch.log
	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:769) [elasticsearch-8.3.3.jar:?]
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-8.3.3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[2022-08-19T16:29:28,904][INFO ][o.e.c.r.a.AllocationService] [rstudio] current.health="GREEN" message="Cluster health status changed from [RED] to [GREEN] (reason: [shards started [[.geoip_databases][0]]])." previous.health="RED" reason="shards started [[.geoip_databases][0]]"
[2022-08-19T16:29:29,175][INFO ][o.e.i.g.DatabaseNodeService] [rstudio] successfully loaded geoip database file [GeoLite2-Country.mmdb]
[2022-08-19T16:29:29,234][INFO ][o.e.i.g.DatabaseNodeService] [rstudio] successfully loaded geoip database file [GeoLite2-ASN.mmdb]
[2022-08-19T16:29:30,032][INFO ][o.e.i.g.DatabaseNodeService] [rstudio] successfully loaded geoip database file [GeoLite2-City.mmdb]
[2022-08-19T16:32:10,413][INFO ][o.e.c.m.MetadataCreateIndexService] [rstudio] [files] creating index, cause [api], templates [], shards [1]/[1]
```

**Comment by Jsalas424** [comment]
I forgot to add spotlight = Yes to the share itself, that fixed it. I realized through the docs here: https://wiki.samba.org/index.php/Spotlight_with_Elasticsearch_Backend#fscrawler

Here's what the final working config looks like

```
[global]
	elasticsearch:port = 9200
	elasticsearch:address = 127.0.0.1
	spotlight backend = elasticsearch

[R Data]
	comment = R Directory Share
	path = /home/jon/R/Data
	read only = No
	spotlight = Yes
```
