### ISSUE TITLE
Enabling Exclude Directories / files from the index

### ISSUE THREAD

**Issue by chrisfield490** [Ellerhold/fs2es-indexer#3]
```
# (Optional) Exclude directories / files from the index
#exclusions:
  # Exclusion via a simple string search in the full path of the file / directory.
  # If any of the given strings are found in the full path, it wont be added to the index.
  # Usually faster than a regular expression!
#  partial_paths:
    - ".DS_Store"
    - "._.DS_Store"
```

When ever I enable this section of the config file, and run a index, I get the below error.

> sudo fs2es-indexer --config=/etc/fs2es_indexer/config.yml index                                        2021-12-03 10:15:23 Reading config file "/etc/fs2es_indexer/config.yml"
Traceback (most recent call last):
  File "/usr/local/bin/fs2es-indexer", line 4, in <module>
    __import__('pkg_resources').run_script('fs2es-indexer==0.3.0', 'fs2es-indexer')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 667, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1470, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.8/dist-packages/fs2es_indexer-0.3.0-py3.8.egg/EGG-INFO/scripts/fs2es-indexer", line 44, in <module>
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
    return loader.get_single_data()
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 392, in parse_block_sequence_entry
    raise ParserError("while parsing a block collection", self.marks[-1],
yaml.parser.ParserError: while parsing a block collection
  in "/etc/fs2es_indexer/config.yml", line 9, column 4
expected <block end>, but found '<block sequence start>'
  in "/etc/fs2es_indexer/config.yml", line 20, column 5

But if I comment these two lines back out, everything runs fine.

**Comment by chrisfield490** [comment]
> Please remove the # from before "exclusions" and "partial_paths". It should look like
> 
> ```yaml
> # (Optional) Exclude directories / files from the index
> exclusions:
>   # Exclusion via a simple string search in the full path of the file / directory.
>   # If any of the given strings are found in the full path, it wont be added to the index.
>   # Usually faster than a regular expression!
>   partial_paths:
>     - ".DS_Store"
>     - "._.DS_Store"
> ```

lol, if you want problems, insert end user :) thank you

**Comment by chrisfield490** [comment]
Thank you, that is now working perfect.

**Comment by MatthiasKuehneEllerhold** [comment]
Happy to help!

**Comment by chrisfield490** [comment]
If i want to exclude any hidden files starting with ._ How is the regular expression defined? is it a standard regular expression or a specific expression in python?

**Comment by MatthiasKuehneEllerhold** [comment]
You can just add it to partial paths - no reg exp needed.
```yaml
# (Optional) Exclude directories / files from the index
exclusions:
  # Exclusion via a simple string search in the full path of the file / directory.
  # If any of the given strings are found in the full path, it wont be added to the index.
  # Usually faster than a regular expression!
  partial_paths:
    - ".DS_Store"
    - "._.DS_Store"
    - "._"
```

**Comment by chrisfield490** [comment]
Perfect. Thank you
