### ISSUE TITLE
ModuleNotFoundError: No module named 'elasticsearch'

### ISSUE THREAD

**Issue by alatteri** [Ellerhold/fs2es-indexer#34]
Hello,

I've followed the instruction and still get the below errors.
RockyLinux 9.2
Elasticsearch installed via official repo.

```
[root@nas02 fs2es-indexer]# systemctl status elasticsearch
● elasticsearch.service - Elasticsearch
     Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; preset: disabled)
     Active: active (running) since Mon 2023-09-18 10:27:05 PDT; 4min 20s ago
       Docs: https://www.elastic.co
   Main PID: 4491 (java)
      Tasks: 147 (limit: 2057900)
     Memory: 32.1G
        CPU: 1min 1.959s
     CGroup: /system.slice/elasticsearch.service
             ├─4491 /usr/share/elasticsearch/jdk/bin/java -Xms4m -Xmx64m -XX:+UseSerialGC -Dcli.name=server -Dcli.script=/usr/share/elasticsearch/bin/elasticsearch -Dcli.libs=lib/tools/server-cli -Des.path.home=/usr/share/elastic>
             ├─4563 /usr/share/elasticsearch/jdk/bin/java -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -Djava.security.manager=allow -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encodin>
             └─4637 /usr/share/elasticsearch/modules/x-pack-ml/platform/linux-x86_64/bin/controller

Sep 18 10:26:53 nas02 systemd[1]: Starting Elasticsearch...
Sep 18 10:27:05 nas02 systemd[1]: Started Elasticsearch.
```

```
[root@nas02 fs2es-indexer]# python3 -m venv --system-site-packages /opt/fs2es-indexer/
[root@nas02 fs2es-indexer]# /opt/fs2es-indexer/bin/pip3 install 'elasticsearch>=8,<9'
Requirement already satisfied: elasticsearch<9,>=8 in ./lib/python3.9/site-packages (8.9.0)
Requirement already satisfied: elastic-transport<9,>=8 in ./lib/python3.9/site-packages (from elasticsearch<9,>=8) (8.4.0)
Requirement already satisfied: urllib3<2,>=1.26.2 in /usr/lib/python3.9/site-packages (from elastic-transport<9,>=8->elasticsearch<9,>=8) (1.26.5)
Requirement already satisfied: certifi in ./lib/python3.9/site-packages (from elastic-transport<9,>=8->elasticsearch<9,>=8) (2023.7.22)
```
```
[root@nas02 fs2es-indexer]# /opt/fs2es-indexer/bin/python3 /opt/fs2es-indexer/fs2es-indexer
2023-09-18 10:33:33 Reading config file "/etc/fs2es-indexer/config.yml"
2023-09-18 10:33:33 Starting indexing run...
Traceback (most recent call last):
  File "/opt/fs2es-indexer/fs2es-indexer", line 80, in <module>
    indexer.elasticsearch_prepare_index()
  File "/opt/fs2es-indexer/lib/Fs2EsIndexer.py", line 144, in elasticsearch_prepare_index
    if self.elasticsearch.indices.exists(index=self.elasticsearch_index):
  File "/opt/fs2es-indexer/lib64/python3.9/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/opt/fs2es-indexer/lib64/python3.9/site-packages/elasticsearch/_sync/client/indices.py", line 1180, in exists
    return self.perform_request(  # type: ignore[return-value]
  File "/opt/fs2es-indexer/lib64/python3.9/site-packages/elasticsearch/_sync/client/_base.py", line 389, in perform_request
    return self._client.perform_request(
  File "/opt/fs2es-indexer/lib64/python3.9/site-packages/elasticsearch/_sync/client/_base.py", line 285, in perform_request
    meta, resp_body = self.transport.perform_request(
  File "/opt/fs2es-indexer/lib64/python3.9/site-packages/elastic_transport/_transport.py", line 329, in perform_request
    meta, raw_data = node.perform_request(
  File "/opt/fs2es-indexer/lib64/python3.9/site-packages/elastic_transport/_node/_http_urllib3.py", line 199, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: ProtocolError(('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))))
```
```
[root@nas02 fs2es-indexer]# /opt/fs2es-indexer/fs2es-indexer index
Traceback (most recent call last):
  File "/opt/fs2es-indexer/fs2es-indexer", line 10, in <module>
    from lib.Fs2EsIndexer import *
  File "/opt/fs2es-indexer/lib/Fs2EsIndexer.py", line 4, in <module>
    import elasticsearch
ModuleNotFoundError: No module named 'elasticsearch'

```

**Comment by gist901** [comment]
If you followed the instructions, then you need to execute using the environment you created, so your code should be:

`/opt/fs2es-indexer/bin/python3 /opt/fs2es-indexer/fs2es-indexer index`

**Comment by alatteri** [comment]
[root@nas02 ~]# /opt/fs2es-indexer/bin/python3 /opt/fs2es-indexer/fs2es-indexer index
2023-09-20 20:15:37 Reading config file "/etc/fs2es-indexer/config.yml"
2023-09-20 20:15:37 Starting indexing run...
Traceback (most recent call last):
  File "/opt/fs2es-indexer/fs2es-indexer", line 80, in <module>
    indexer.elasticsearch_prepare_index()
  File "/opt/fs2es-indexer/lib/Fs2EsIndexer.py", line 144, in elasticsearch_prepare_index
    if self.elasticsearch.indices.exists(index=self.elasticsearch_index):
  File "/opt/fs2es-indexer/lib64/python3.9/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/opt/fs2es-indexer/lib64/python3.9/site-packages/elasticsearch/_sync/client/indices.py", line 1180, in exists
    return self.perform_request(  # type: ignore[return-value]
  File "/opt/fs2es-indexer/lib64/python3.9/site-packages/elasticsearch/_sync/client/_base.py", line 389, in perform_request
    return self._client.perform_request(
  File "/opt/fs2es-indexer/lib64/python3.9/site-packages/elasticsearch/_sync/client/_base.py", line 285, in perform_request
    meta, resp_body = self.transport.perform_request(
  File "/opt/fs2es-indexer/lib64/python3.9/site-packages/elastic_transport/_transport.py", line 329, in perform_request
    meta, raw_data = node.perform_request(
  File "/opt/fs2es-indexer/lib64/python3.9/site-packages/elastic_transport/_node/_http_urllib3.py", line 199, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: ProtocolError(('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))))

> If you followed the instructions, then you need to execute using the environment you created, so your code should be:
> 
> `/opt/fs2es-indexer/bin/python3 /opt/fs2es-indexer/fs2es-indexer index`

**Comment by alatteri** [comment]
I can also confirm ES is running via:

 `curl --cacert /etc/elasticsearch/certs/http_ca.crt -u elastic:XXXXXXX https://localhost:9200 `
```
{
  "name" : "nas02",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "bYGyhQVxTfagNMG8t4CwTg",
  "version" : {
    "number" : "8.10.1",
    "build_flavor" : "default",
    "build_type" : "rpm",
    "build_hash" : "a94744f97522b2b7ee8b5dc13be7ee11082b8d6b",
    "build_date" : "2023-09-14T20:16:27.027355296Z",
    "build_snapshot" : false,
    "lucene_version" : "9.7.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by alatteri** [comment]
OK...this comes down to the fact that I was using an non-ssl URL, `url: "http://localhost:9200"`
Switching to https and  setting `verify_certs: False` and `ssl_show_warn: False` now works.

There is mention of `only if use_ssl == True` but that token does not exist in the config file.
