### ISSUE TITLE
Getting elastic_transport.ConnectionError When Attempting to Run Index

### ISSUE THREAD

**Issue by gist901** [Ellerhold/fs2es-indexer#35]
Hello, 

I have followed the steps provided, but when I tried executing the Index, I recieved the following error message:

`2023-09-20 20:28:07 Reading config file "/etc/fs2es-indexer/config.yml"
2023-09-20 20:28:07 Starting indexing run...
Traceback (most recent call last):
  File "/opt/fs2es-indexer/fs2es-indexer", line 80, in <module>
    indexer.elasticsearch_prepare_index()
  File "/opt/fs2es-indexer/lib/Fs2EsIndexer.py", line 144, in elasticsearch_prepare_index
    if self.elasticsearch.indices.exists(index=self.elasticsearch_index):
  File "/opt/fs2es-indexer/lib/python3.9/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/opt/fs2es-indexer/lib/python3.9/site-packages/elasticsearch/_sync/client/indices.py", line 1180, in exists
    return self.perform_request(  # type: ignore[return-value]
  File "/opt/fs2es-indexer/lib/python3.9/site-packages/elasticsearch/_sync/client/_base.py", line 389, in perform_request
    return self._client.perform_request(
  File "/opt/fs2es-indexer/lib/python3.9/site-packages/elasticsearch/_sync/client/_base.py", line 285, in perform_request
    meta, resp_body = self.transport.perform_request(
  File "/opt/fs2es-indexer/lib/python3.9/site-packages/elastic_transport/_transport.py", line 329, in perform_request
    meta, raw_data = node.perform_request(
  File "/opt/fs2es-indexer/lib/python3.9/site-packages/elastic_transport/_node/_http_urllib3.py", line 199, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: ProtocolError(('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))))`

If I test to see if my ElasticSearch is up and running I recieve the following response:

`root@omv:/opt# curl --cacert /etc/elasticsearch/certs/http_ca.crt -u elastic:$ELASTIC_PASSWORD https://localhost:9200 
{
  "name" : "omv",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "qZ226fbFTde4YFphg63VgA",
  "version" : {
    "number" : "8.10.1",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "a94744f97522b2b7ee8b5dc13be7ee11082b8d6b",
    "build_date" : "2023-09-14T20:16:27.027355296Z",
    "build_snapshot" : false,
    "lucene_version" : "9.7.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}`

Any help or thoughts would be greatly appreciated

**Comment by alatteri** [comment]
see https://github.com/Ellerhold/fs2es-indexer/issues/34

**Comment by MatthiasKuehneEllerhold** [comment]
@gist901 Is this issue still present? Did @alatteri hint help you?
If not: please post your `config.yml` so I can try to help you :)
