### ISSUE TITLE
Can't get fs2es-indexer to start

### ISSUE THREAD

**Issue by rcto998** [Ellerhold/fs2es-indexer#40]
on ubuntu 24.04
tried to follow all instructions for install... elasticsearch seems to be running fine
installed fs2es-indexer in the venv
running any of the indexer tasks seems like it has to be done this way (as not including the first part doesn't work and complains it can't find elasticsearch):
"/opt/fs2es-indexer/bin/python3 /opt/fs2es-indexer/fs2es-indexer daemon" but doesn't seem to do anything and prints a bunch of stuff in the terminal:

Traceback (most recent call last):
  File "/opt/fs2es-indexer/fs2es-indexer", line 73, in <module>
    config = yaml.safe_load(stream)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/yaml/parser.py", line 438, in parse_block_mapping_key
    raise ParserError("while parsing a block mapping", self.marks[-1],
yaml.parser.ParserError: while parsing a block mapping
  in "/etc/fs2es-indexer/config.yml", line 6, column 1
expected <block end>, but found '<block sequence start>'
  in "/etc/fs2es-indexer/config.yml", line 16, column 5

unfortunately, I'm completely lost as to what to try now

**Comment by MatthiasKuehneEllerhold** [comment]
Your config file "/etc/fs2es-indexer/config.yml" seems to be malformed. Please make sure that its correct YAML. Check indents, colons (":"), etc.

**Comment by rcto998** [comment]
thanks for that, I did config and I think I found the errors, but still can't get fs2es to start... I don't think I'm savvy enough to get this working - I just enabled tracker option in samba instead of elasticsearch and that is working right away, so I think I'm going to go with that instead as it's installed by default in ubuntu anyways
